#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
IFS=" "
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
exec 2>/var/log/$(basename $0).log
source /usr/bin/variables
rootcli

contar=0
for i in $(ps -A -ostat,ppid | grep -e '[zZ]' | awk '{print $2}'); do
	echo "Enviando señal SIGCHLD al proceso con el PID $i"
	kill -s SIGCHLD $i
	let contar=$(($contar+1))
done

for j in $(ps -A -ostat,ppid | grep -e '[zZ]' | awk '{print $2}'); do
	echo "Enviando señal SIGHUP al proceso con el PID $j"
	kill -s SIGHUP $j
done

echo "Se han encontrado $contar procesos zombie"
echo "Finalizado."
rm -f /run/$(basename $0).pid
exit 0
