#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debe ser ROOT\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid

contar=0
for i in $(ps -A -ostat,ppid | grep -e '[zZ]' | awk '{print $2}'); do
	echo "Enviando señal SIGCHLD al proceso con el PID $i"
	kill -s SIGCHLD $i
	let contar=$(($contar+1))
done

for j in $(ps -A -ostat,ppid | grep -e '[zZ]' | awk '{print $2}'); do
	echo "Enviando señal SIGHUP al proceso con el PID $j"
	kill -s SIGHUP $j
done

echo "Se han encontrado $contar procesos zombie"
echo "Finalizado."
rm -f /run/$(basename $0).pid
exit 0
